//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.0
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClipTex.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ClipTex.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die #Line breaks
        ///\\
        ///\kill
        ///\noindent
        ///#Math
        ///\frac{•}{•}
        ///\int
        ///\sum
        ///\sum_{•}^•
        ///\mathbf{•}
        ///\leq
        ///\times
        ///\circ
        ///\infty
        ///\supset
        ///\subset
        ///\cup
        ///\dot •
        ///\alpha
        ///\epsilon
        ///\theta
        ///\lambda
        ///\pi
        ///\sqrt{•}
        ///\sqrt[•]{•}
        ///\prod
        ///\prod_{•}^•
        ///\lambda
        ///\pi
        ///\upsilon
        ///\omega
        ///\Lambda
        ///\Upsilon
        ///\geq
        ///\div
        ///\circ
        ///\neg
        ///\forall
        ///\exists
        ///\cap
        ///\hat •
        ///\beta
        ///\zeta
        ///\iota
        ///\mu
        ///\rho
        ///\phi
        ///\Gamma
        ///\Xi
        ///\Phi
        ///\neq
        ///\pm
        ///\prime
        ///\wedge
        ///\in
        ///\notin
        ///\mid
        ///\bar •
        ///\gamma
        ///\eta
        ///\kappa
        ///\nu
        ///\sigma
        ///\chi
        ///\Delta
        ///\Pi
        ///\Ps [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string LatexCommands {
            get {
                return ResourceManager.GetString("LatexCommands", resourceCulture);
            }
        }
    }
}
